### ISSUE TITLE
swift_version

### ISSUE THREAD

**Issue by pengStyle** [attaswift/BigInt#112]
Please add "spec.swift_version = '5.0' " in podspec file on lastest Version

**Comment by koraykoska** [comment]
I don't think Cocoapods is supported anymore. Please use SPM.

**Comment by ypopovych** [comment]
@koraykoska Could you, please, try to support CocoaPods? You can republish it with different names `BigInteger`, `BigInt.swift`, etc.  There are a lot of libraries that depend on it on CocoaPods :(

**Comment by koraykoska** [comment]
@ypopovych Cocoapods is a deprecated package manager. On top of that it has always been broken from the core. I do not support legacy technology and there is no reason to use a package via Cocoapods instead of SPM as of today. If the "tons of libraries" you are talking about are all Cocoapods only, consider them legacy and don't touch them. There is literally zero reason for a maintained library to not simply add a `Package.swift`. It's 5 minutes of work.

**Comment by pengStyle** [comment]
We use BigInt in the Kotlin Multiplatform Mobile（KMM）, It use Cocoapods for package manager

**Comment by koraykoska** [comment]
@pengStyle Using KMM is a choice that comes with undeniable pros and very tough cons. I once used it in a production app and would never do it again. Besides, it's alpha software and its engineers obviously don't understand the Apple platform, otherwise, they would have never chosen to go with Cocoapods.

Do what @tgymnich mentioned and don't try to force a legacy technology on modern libraries just because you made bad decisions.
