### ISSUE TITLE
Xcode 9, swift 3

### ISSUE THREAD

**Issue by dropski** [attaswift/BigInt#27]
The new version (3.0.0) of BigInt doesn't compile on Xcode 9, are there any chance for support swift 3.2 ?

**Comment by dagerydoo** [comment]
I noticed that if I remove the keyword `private` from [kind and storage](https://github.com/attaswift/BigInt/blob/f2a3c28ce44a8e8ed9cc576d779861d4145bae0e/sources/BigUInt.swift#L30-L31),  things compiled for me. Thus ending up with:

```
    internal (set) var kind: Kind // Internal for testing only
    internal (set) var storage: [Word] // Internal for testing only; stored separately to prevent COW copies
```

I don't entirely get this, as the [swift docs](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html) seem to indicate the `private` should work:

> Private access restricts the use of an entity to the enclosing declaration, and to extensions of that declaration that are in the same file. Use private access to hide the implementation details of a specific piece of functionality when those details are used only within a single declaration.

However, I don't see the value of `private` is here, especially since it is breaking things. `internal` seems sufficient, but I am sure others have different opinions.

**Comment by dagerydoo** [comment]
Reading the comment again, I realize that they only want `set` statements in the source file, but otherwise allow tests to read the result.

**Comment by dagerydoo** [comment]
OK, this is probably a happy medium:

```
    internal fileprivate (set) var kind: Kind // Internal for testing only
    internal fileprivate (set) var storage: [Word] // Internal for testing only; stored separately to prevent COW copies
```

**Comment by dagerydoo** [comment]
https://github.com/attaswift/BigInt/pull/29

**Comment by lorentey** [comment]
Merged! Thanks 🙏🏻
