### ISSUE TITLE
Performance vs accelerate/veclib/vbignum ?

### ISSUE THREAD

**Issue by Sajjon** [attaswift/BigInt#43]
Hey! Thanks for this amazing `BigInt` lib! I am curious if there has been any benchmark vs https://developer.apple.com/documentation/accelerate/veclib/vbignum ? Otherwise I might do a PR with some unit tests doing a benchmark - if at all interesting?

**Comment by Ybrin** [comment]
There are none but I can tell you the results. vBigNum will perform much
better as Apples libraries are extremely optimized for their specific tasks.

The reason why BigInt exists is because it has theoretically no limits and
is a real BigInteger library. vBigNum is limited to 1024 bits.
And we also have Linux support, which is still missing in vBigNum (at least
I think so...).

But you can still go ahead and add some tests if you want to.

**Comment by Sajjon** [comment]
Might add performance tests in the future, closing for now, thx @Ybrin !
