### ISSUE TITLE
DYLIB_COMPATIBILITY_VERSION mismatch between Carthage and CocoaPods

### ISSUE THREAD

**Issue by armcknight** [attaswift/BigInt#73]
I have an admittedly niche scenario, where some parts of my project pull in `BigInt` via Carthage, but others use CocoaPods. 

Carthage picks up `DYLIB_COMPATIBILITY_VERSION` set in `BigInt.xcodeproj` with `BUILD_NUMBER` from your xcconfig, but CocoaPods doesn't use the xcodeproj in your repo. So the mismatched `DYLIB_COMPATIBILITY_VERSION` values in the various load commands causes a runtime crash in one of my apps.

There are some options for making the build outputs of both package managers more similar:

1) Include the following in your podspec: 
```ruby
spec.pod_target_xcconfig = { "DYLIB_COMPATIBILITY_VERSION" => "<build-number>"}
```

You'd probably want to automate injecting the xcconfig's value into that; less ideally, you'd need to manually update it in both places each release. 

2) Alternatively, you could consider not setting the `DYLIB_COMPATIBILITY_VERSION` at all in your xcodeproj, so that you get the same build output from Carthage that you get from CocoaPods today, with a value of `1`.

I'm currently working around this issue with a `post_install` hook that sets the same value, hardcoded to the value I look up in your releases.

🙏 I'm totally fine with this issue being closed as #wontfix because this really comes down to the difference in how the package managers work, not just your library. Anyways, thank you for your time and for your code!

**Comment by TG908** [comment]
There are 4 ways to build BigInt at the moment:
| | Version | DYLIB_COMPATIBILITY_VERSION  |
|----|-----|---|
| manually | 5.1.0 | 15 |
| Carthage | 5.1.0 | 15 |
| Swift Package Manager  | 0.0.0  | 0.0.0 |
| Cocoa Pods  | 5.1.0 | 1 |

If we were to fix cocoa pods there would still be an issue with swift package manager. Also once we add `spec.pod_target_xcconfig = { "DYLIB_COMPATIBILITY_VERSION" => "<build-number>"}` we cannot easily remove it again, since it would break future builds. Because of this I would prefer to leave it up to the respective package manager to handle `DYLIB_COMPATIBILITY_VERSION`.
